### PR TITLE
Make sure we don't trim away important data

### PR DESCRIPTION
**Pull request by Nyholm**
We can know the length of EOL character.

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you @goetas for your thumbs up. I saw that you also have worked on these lines of code.

**Comment by goetas** [comment]
Hi, yeah, was about https://github.com/goetas/MultipartUploadBundle

Nice to see other people contributing to this project.

**Comment by rcambien** [comment]
Thank @Nyholm for the contribution.

Can you explain me the context of this PR ? I had very strange behaviour with mixed EOL multipart, it's why I fixed the length and added and option for this.

**Comment by Nyholm** [comment]
Hm. Who would use mixed EOLs? I did not think about that. 

Maybe we should have “auto detect” or used the predefined EOL length.

**Comment by jkrzefski** [comment]
@Nyholm Here is my attempt to implement "auto-detect" for EOL character length. There are similarities to your proposed changes. What do you think about this? https://github.com/Riverline/multipart-parser/pull/46

**Pull request closed without merging**
