### PR TITLE
Bugfix for large files

### PR DESCRIPTION
**Pull request by PaulCombal**
I guess regexes are too expensive for large files. This is the only way I could get this to work.

### CODE REVIEW

**Comment by rcambien** [comment]
Hi @PaulCombal 
I used Regex to parse of multipart content with inconsistent end of line.
I know that is not the best solution but in my use case, I got this problem a lot.

What you can do, is configure PHP to allow the parsing of bigger string with the `pcre.backtrack_limit` parameter (https://secure.php.net/manual/fr/pcre.configuration.php)

I can look at a better solution but I must keep current compatibility.

**Comment by PaulCombal** [comment]
Alright then, feel free to close the pull request, even though I feel it could save a lot of time to other people. 
Of course the code isn't perfect and is just a way to find a temporary bugfix.
And if you must keep compatibility, why not specify a version number in your composer.json?

**Comment by rcambien** [comment]
Sorry but I must keep backward compatibility.
I understand that the solution I choose is not the best for performance and I will try to find something that solve your problem and is backward compatible.

I let this PR open to follow the issue.

**Comment by rcambien** [comment]
Hi @PaulCombal 
I just realeased version 2 of the lib that use streams.
You can give it a try !

**Pull request closed without merging**
