### PR TITLE
Fixes an issue with processing very large multi-part files.

### PR DESCRIPTION
**Pull request by BrunoDeBarros**
One of the regexes makes use of backtracking, which breaks for very large strings due to the `pcre.backtrack_limit`, which defaults to 1000000 (~1MB). 

This PR adjust the backtrack limit specifically for that situation, and includes a unit test to confirm that the broken behaviour is now resolved.

### CODE REVIEW

**Comment by rcambien** [comment]
Thanks for the PR Bruno,

Can you check why the test failed with PHP 7 ? 
https://travis-ci.org/Riverline/multipart-parser/jobs/415334418

Also, to avoid storing large files on the repository, can you change your test to use generated content ?

This PR also solve #16

**Comment by BrunoDeBarros** [comment]
I've now changed the test to use generated content. The issue with PHP 7.0+ seems to have been caused by it needing an even larger backtrack limit than just the size of the content. `strlen($content) * 2` does the trick.

**Comment by BrunoDeBarros** [comment]
@rcambien The tests for 5.5 and 5.3 have failed but it's not related to my code; seems to be an issue with running the tests. The tests for every other version of PHP seem fine. 

Is there anything I can do to help get this PR through?

**Comment by rcambien** [comment]
Hi @BrunoDeBarros 
I just released the version 2 of the lib that don't use preg function.
It should solve your problem.

**Pull request closed without merging**
